import type { PagesFunction } from '@cloudflare/workers-types';
import { type Env, requirePermission, jsonOk, jsonError, serverError } from '../../lib/session';
import { sendEmail, calendarEventEmail } from '../../lib/email';

function serializeEvent(r: Record<string, unknown>, propertyIds?: string[]) {
  return {
    id: r.id,
    propertyId: r.property_id ?? undefined,
    propertyIds: propertyIds ?? (r.property_id ? [r.property_id as string] : []),
    unitId: r.unit_id ?? undefined,
    title: r.title,
    description: r.description ?? undefined,
    category: r.category,
    eventDate: r.event_date,
    endDate: r.end_date ?? undefined,
    eventTime: r.event_time ?? undefined,
    endTime: r.end_time ?? undefined,
    priority: r.priority ?? 'medium',
    isRecurring: !!r.is_recurring,
    recurrenceRule: r.recurrence_rule ?? undefined,
    completed: !!r.completed,
    completedAt: r.completed_at ?? undefined,
    notes: r.notes ?? undefined,
    reminderHours: r.reminder_hours != null ? Number(r.reminder_hours) : undefined,
    createdAt: r.created_at,
    isAuto: !!r.is_auto,
    visibility: (r.visibility as string) || 'shared',
    userId: r.user_id ?? undefined,
  };
}

async function getPropertyIdsForEvents(env: Env, eventIds: string[]): Promise<Map<string, string[]>> {
  if (eventIds.length === 0) return new Map();
  const { results } = await env.DB.prepare(
    `SELECT event_id, property_id FROM calendar_event_properties WHERE event_id IN (${eventIds.map(() => '?').join(',')})`,
  ).bind(...eventIds).all();
  const map = new Map<string, string[]>();
  for (const r of (results || [])) {
    const eid = r.event_id as string;
    if (!map.has(eid)) map.set(eid, []);
    map.get(eid)!.push(r.property_id as string);
  }
  return map;
}

async function syncEventProperties(env: Env, eventId: string, propertyIds: string[]) {
  await env.DB.prepare('DELETE FROM calendar_event_properties WHERE event_id = ?').bind(eventId).run();
  if (propertyIds.length > 0) {
    const values = propertyIds.map(() => '(?, ?)').join(', ');
    const binds: string[] = [];
    for (const pid of propertyIds) { binds.push(eventId, pid); }
    await env.DB.prepare(
      `INSERT OR IGNORE INTO calendar_event_properties (event_id, property_id) VALUES ${values}`
    ).bind(...binds).run();
  }
}

async function notifyAdmins(env: Env, type: 'created' | 'updated' | 'cancelled', eventRow: Record<string, unknown>, propertyIds?: string[]) {
  const admins = await env.DB.prepare(
    `SELECT email FROM user WHERE role IN ('super_admin', 'admin') AND email IS NOT NULL`
  ).all();
  const emails = (admins.results || []).map(r => r.email as string).filter(Boolean);
  if (emails.length === 0) return;

  let propertyName: string | undefined;
  const pids = propertyIds ?? (eventRow.property_id ? [eventRow.property_id as string] : []);
  if (pids.length > 0) {
    const placeholders = pids.map(() => '?').join(',');
    const { results } = await env.DB.prepare(
      `SELECT name, address FROM properties WHERE id IN (${placeholders})`
    ).bind(...pids).all();
    propertyName = (results || []).map(r => (r.name || r.address) as string).filter(Boolean).join(', ');
  }

  const unitRow = eventRow.unit_id
    ? ((await env.DB.prepare('SELECT unit_number FROM units WHERE id = ?').bind(eventRow.unit_id).first()) as { unit_number?: string } | null)
    : null;

  const email = calendarEventEmail({
    type,
    title: eventRow.title as string,
    eventDate: eventRow.event_date as string,
    propertyName: propertyName || undefined,
    unitLabel: unitRow?.unit_number ? `Unit ${unitRow.unit_number}` : undefined,
    description: (eventRow.description as string) || undefined,
    category: (eventRow.category as string) || undefined,
    priority: (eventRow.priority as string) || undefined,
  });

  for (const to of emails) {
    await sendEmail(env, { to, ...email });
  }
}

/** Generate synthetic calendar events from lease milestones and user birthdays. */
async function autoGeneratedEvents(env: Env): Promise<Record<string, unknown>[]> {
  const auto: Record<string, unknown>[] = [];

  // 1. Lease milestones: expiration, renewal start_date, termination (ended status),
  //    and move-in (lease start_date).
  try {
    const { results: leases } = await env.DB.prepare(
      `SELECT l.id, l.start_date, l.end_date, l.status, l.end_reason,
              l.property_id, l.unit_id,
              p.name AS prop_name, p.address AS prop_addr,
              u.unit_number,
              GROUP_CONCAT(t.first_name || ' ' || t.last_name, ', ') AS tenant_names
         FROM leases l
         LEFT JOIN properties p ON p.id = l.property_id
         LEFT JOIN units u ON u.id = l.unit_id
         LEFT JOIN lease_tenants lt ON lt.lease_id = l.id
         LEFT JOIN tenants t ON t.id = lt.tenant_id
        GROUP BY l.id`
    ).all();
    const propLabel = (r: Record<string, unknown>) => {
      const parts: string[] = [];
      if (r.prop_name || r.prop_addr) parts.push((r.prop_name || r.prop_addr) as string);
      if (r.unit_number) parts.push(`Unit ${r.unit_number}`);
      return parts.join(', ');
    };

    for (const l of (leases || []) as Record<string, unknown>[]) {
      const loc = propLabel(l);
      const who = (l.tenant_names as string) || 'Unknown';

      // Move-in date
      if (l.start_date) {
        auto.push({
          id: `auto-movein-${l.id}`, property_id: l.property_id, unit_id: l.unit_id,
          title: `Move In: ${who}`, description: loc,
          category: 'move_in', event_date: l.start_date, priority: 'medium',
          is_recurring: 0, completed: 0, is_auto: 1,
        });
      }

      // Lease expiration
      if (l.end_date && l.status !== 'ended') {
        auto.push({
          id: `auto-expiry-${l.id}`, property_id: l.property_id, unit_id: l.unit_id,
          title: `Lease Expires: ${who}`, description: loc,
          category: 'lease_expiration', event_date: l.end_date, priority: 'high',
          is_recurring: 0, completed: 0, is_auto: 1,
        });
      }

      // Lease termination (ended leases with an end_date)
      if (l.status === 'ended' && l.end_date) {
        auto.push({
          id: `auto-term-${l.id}`, property_id: l.property_id, unit_id: l.unit_id,
          title: `Lease Terminated: ${who}`,
          description: l.end_reason ? `${loc} (${l.end_reason})` : loc,
          category: 'lease_termination', event_date: l.end_date, priority: 'medium',
          is_recurring: 0, completed: 1, is_auto: 1,
        });
      }
    }
  } catch { /* pre-migration safe */ }

  // 2. Team member birthdays (annually recurring, shown in current year).
  try {
    const { results: users } = await env.DB.prepare(
      `SELECT u.id, u.name, u.birthdate
         FROM user u
         JOIN user_roles r ON r.user_id = u.id
        WHERE u.birthdate IS NOT NULL AND u.is_active = 1
          AND r.role NOT IN ('tenant', 'realtor', 'handyman')`
    ).all();
    for (const u of (users || []) as Record<string, unknown>[]) {
      const bd = u.birthdate as string; // YYYY-MM-DD
      const monthDay = bd.substring(5);  // MM-DD
      const name = (u.name as string) || 'Team Member';
      auto.push({
        id: `auto-bday-${u.id}`, title: `🎂 ${name}'s Birthday`,
        category: 'birthday', event_date: bd,
        priority: 'low', is_recurring: 1, recurrence_rule: 'annually',
        completed: 0, is_auto: 1, description: monthDay,
      });
    }
  } catch { /* pre-migration safe */ }

  // 3. Scheduled maintenance requests — show on the calendar when a date/time
  //    has been confirmed (status = scheduled, in_progress, or completed with a
  //    scheduled_for value). Completed requests are marked done on the calendar.
  try {
    const { results: maint } = await env.DB.prepare(
      `SELECT m.id, m.title, m.description, m.priority, m.status,
              m.property_id, m.unit_id, m.scheduled_for,
              p.name AS prop_name, p.address AS prop_addr,
              u.unit_number,
              t.first_name || ' ' || t.last_name AS tenant_name,
              h.name AS handyman_name
         FROM maintenance_requests m
         LEFT JOIN properties p ON p.id = m.property_id
         LEFT JOIN units u ON u.id = m.unit_id
         LEFT JOIN tenants t ON t.id = m.tenant_id
         LEFT JOIN user h ON h.id = m.assigned_handyman_id
        WHERE m.scheduled_for IS NOT NULL
          AND m.status NOT IN ('cancelled')`
    ).all();
    for (const m of (maint || []) as Record<string, unknown>[]) {
      const sf = m.scheduled_for as string; // 'YYYY-MM-DD HH:MM' or 'YYYY-MM-DD'
      const date = sf.substring(0, 10);
      const time = sf.length > 10 ? sf.substring(11) : undefined;
      const locParts: string[] = [];
      if (m.prop_name || m.prop_addr) locParts.push((m.prop_name || m.prop_addr) as string);
      if (m.unit_number) locParts.push(`Unit ${m.unit_number}`);
      const loc = locParts.join(', ');
      const who = (m.handyman_name as string) || 'Unassigned';
      const tenant = (m.tenant_name as string) || '';
      const desc = [loc, tenant ? `Tenant: ${tenant}` : '', who !== 'Unassigned' ? `Assigned: ${who}` : ''].filter(Boolean).join(' · ');
      const done = ['completed', 'resolved'].includes(m.status as string);

      auto.push({
        id: `auto-maint-${m.id}`, property_id: m.property_id, unit_id: m.unit_id,
        title: `🔧 ${(m.title as string) || 'Maintenance'}`,
        description: desc,
        category: 'maintenance', event_date: date,
        event_time: time, priority: m.priority || 'medium',
        is_recurring: 0, completed: done ? 1 : 0, is_auto: 1,
      });
    }
  } catch { /* pre-migration safe */ }

  // 4. Appliance warranty expirations — show on the calendar so the office
  //    sees upcoming and recently expired warranties at a glance.
  try {
    const { results: appliances } = await env.DB.prepare(
      `SELECT a.id, a.type, a.brand, a.warranty_expiration,
              a.property_id, a.unit_id,
              p.name AS prop_name, p.address AS prop_addr,
              u.unit_number
         FROM appliances a
         LEFT JOIN properties p ON p.id = a.property_id
         LEFT JOIN units u ON u.id = a.unit_id
        WHERE a.warranty_expiration IS NOT NULL`
    ).all();

    const typeLabels: Record<string, string> = {
      refrigerator: 'Refrigerator', stove_oven: 'Stove/Oven', dishwasher: 'Dishwasher',
      washer: 'Washer', dryer: 'Dryer', hvac: 'HVAC', water_heater: 'Water Heater',
      microwave: 'Microwave', garbage_disposal: 'Garbage Disposal', furnace: 'Furnace',
      air_conditioner: 'Air Conditioner', range_hood: 'Range Hood', freezer: 'Freezer',
      other: 'Appliance',
    };

    for (const a of (appliances || []) as Record<string, unknown>[]) {
      const locParts: string[] = [];
      if (a.prop_name || a.prop_addr) locParts.push((a.prop_name || a.prop_addr) as string);
      if (a.unit_number) locParts.push(`Unit ${a.unit_number}`);
      const loc = locParts.join(', ');

      const appType = typeLabels[a.type as string] || (a.type as string);
      const brandLabel = a.brand ? ` (${a.brand})` : '';

      auto.push({
        id: `auto-warranty-${a.id}`,
        property_id: a.property_id,
        unit_id: a.unit_id ?? null,
        title: `⚠️ Warranty Expires: ${appType}${brandLabel}`,
        description: loc,
        category: 'warranty_expiration',
        event_date: a.warranty_expiration,
        priority: 'medium',
        is_recurring: 0,
        completed: 0,
        is_auto: 1,
      });
    }
  } catch { /* pre-migration safe */ }

  return auto;
}

export const onRequestGet: PagesFunction<Env> = async (context) => {
  const { env, request } = context;
  const auth = await requirePermission(env, request, 'finances_view');
  if (auth instanceof Response) return auth;

  try {
    // Return shared events + only this user's personal events.
    const { results } = await env.DB.prepare(
      `SELECT * FROM calendar_events
        WHERE visibility = 'shared'
           OR user_id = ?
        ORDER BY event_date ASC`
    ).bind(auth.id).all();
    const rows = (results || []) as Record<string, unknown>[];
    const eventIds = rows.map(r => r.id as string);
    const propMap = await getPropertyIdsForEvents(env, eventIds);

    const manual = rows.map(r => serializeEvent(r, propMap.get(r.id as string) || []));
    const auto = (await autoGeneratedEvents(env)).map(r => serializeEvent(r));
    return jsonOk({ success: true, data: [...manual, ...auto] });
  } catch {
    return serverError();
  }
};

export const onRequestPost: PagesFunction<Env> = async (context) => {
  const { env, request } = context;
  const auth = await requirePermission(env, request, 'finances_expenses');
  if (auth instanceof Response) return auth;

  try {
    const body = (await request.json()) as Record<string, unknown>;
    if (!body.title || !body.category || !body.eventDate) {
      return jsonError('Title, category, and event date are required', 400);
    }

    const propertyIds = Array.isArray(body.propertyIds) ? (body.propertyIds as string[]).filter(Boolean) : [];
    const primaryPropertyId = propertyIds[0] ?? (body.propertyId as string) ?? null;

    const id = crypto.randomUUID();
    const visibility = body.visibility === 'personal' ? 'personal' : 'shared';
    await env.DB.prepare(
      `INSERT INTO calendar_events (id, property_id, unit_id, title, description, category, event_date, end_date, event_time, end_time, priority, is_recurring, recurrence_rule, notes, user_id, reminder_hours, visibility)
       VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`
    ).bind(
      id,
      primaryPropertyId,
      body.unitId ?? null,
      body.title,
      body.description ?? null,
      body.category,
      body.eventDate,
      body.endDate ?? null,
      body.eventTime ?? null,
      body.endTime ?? null,
      body.priority ?? 'medium',
      body.isRecurring ? 1 : 0,
      body.recurrenceRule ?? null,
      body.notes ?? null,
      auth.id,
      body.reminderHours ?? null,
      visibility,
    ).run();

    if (propertyIds.length > 0) {
      await syncEventProperties(env, id, propertyIds);
    } else if (primaryPropertyId) {
      await syncEventProperties(env, id, [primaryPropertyId]);
    }

    const row = await env.DB.prepare('SELECT * FROM calendar_events WHERE id = ?').bind(id).first();
    const pids = propertyIds.length > 0 ? propertyIds : (primaryPropertyId ? [primaryPropertyId] : []);
    context.waitUntil(notifyAdmins(env, 'created', row as Record<string, unknown>, pids));
    return jsonOk({ success: true, data: serializeEvent(row as Record<string, unknown>, pids) }, 201);
  } catch {
    return serverError();
  }
};
